/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chessgui;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author tylar
 */
public class SettingsPanel extends javax.swing.JPanel {

    private DefaultListModel allHistoryList, gameHistoryList;
    private MainFrame mainFrame;
    private ArrayList<ArrayList <String>> gamesHistory;
    private Image board1, board2, board3, pieces1, pieces2, pieces3;
    private FlowLayout boardsLayout, piecesLayout;
    private JLabel B1Label, B2Label, B3Label, P1Label, P2Label, P3Label;
    private ButtonGroup boardsGroup, piecesGroup;
    
    public SettingsPanel(MainFrame mainFrame) throws IOException, FileNotFoundException, ClassNotFoundException{
        initComponents();
        this.mainFrame = mainFrame;
        this.gamesHistory = mainFrame.getAllHistory();
        this.allHistoryList = new DefaultListModel();
        
        this.boardsGroup = new ButtonGroup();
        this.boardsGroup.add(Board1Button);
        this.boardsGroup.add(Board2Button);
        this.boardsGroup.add(Board3Button);
        
        this.piecesGroup = new ButtonGroup();
        this.piecesGroup.add(Pieces1Button);
        this.piecesGroup.add(Pieces2Button);
        this.piecesGroup.add(Pieces3Button);
        
        for(int x=0; x < gamesHistory.size(); x++){
            allHistoryList.addElement(gamesHistory.get(x));
        }
        HistoryList = new JList(allHistoryList);
        HistoryListPane.setViewportView(HistoryList);
        HistoryList.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        
        createImages();
    }
    
    private void createImages() throws IOException{
        this.boardsLayout = new FlowLayout();
        this.boardsLayout.setHgap(5);
        this.BoardPanel.setLayout(boardsLayout);
        
        board1 = ImageIO.read(new File("images/board.png"));
        board2 = ImageIO.read(new File("images/board2.png"));
        board3 = ImageIO.read(new File("images/board3.png"));
        
        this.board1 = board1.getScaledInstance(125, 125, BufferedImage.SCALE_SMOOTH);
        this.board2 = board2.getScaledInstance(125, 125, BufferedImage.SCALE_SMOOTH);
        this.board3 = board3.getScaledInstance(125, 125, BufferedImage.SCALE_SMOOTH);
        
        B1Label = new JLabel(new ImageIcon(board1));
        B2Label = new JLabel(new ImageIcon(board2));
        B3Label = new JLabel(new ImageIcon(board3));
        
        BoardPanel.add(B1Label);
        BoardPanel.add(B2Label);
        BoardPanel.add(B3Label);
        
        
        this.piecesLayout = new FlowLayout();
        this.piecesLayout.setHgap(5);
        this.PiecesPanel.setLayout(piecesLayout);
        
        pieces1 = ImageIO.read(new File("images/white_pieces/queen.png"));
        pieces2 = ImageIO.read(new File("images/white_pieces2/queen.png"));
        pieces3 = ImageIO.read(new File("images/white_pieces3/queen.png"));
        
        this.pieces1 = pieces1.getScaledInstance(125, 125, BufferedImage.SCALE_SMOOTH);
        this.pieces2 = pieces2.getScaledInstance(125, 125, BufferedImage.SCALE_SMOOTH);
        this.pieces3 = pieces3.getScaledInstance(125, 125, BufferedImage.SCALE_SMOOTH);
        
        P1Label = new JLabel(new ImageIcon(pieces1));
        P2Label = new JLabel(new ImageIcon(pieces2));
        P3Label = new JLabel(new ImageIcon(pieces3));
        
        PiecesPanel.add(P1Label);
        PiecesPanel.add(P2Label);
        PiecesPanel.add(P3Label);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ExpandButton = new javax.swing.JButton();
        HistoryPanel = new javax.swing.JPanel();
        HistoryListPane = new javax.swing.JScrollPane();
        HistoryList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        BoardPanel = new javax.swing.JPanel();
        Board1Button = new javax.swing.JToggleButton();
        Board2Button = new javax.swing.JToggleButton();
        Board3Button = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        PiecesPanel = new javax.swing.JPanel();
        Pieces1Button = new javax.swing.JToggleButton();
        Pieces2Button = new javax.swing.JToggleButton();
        Pieces3Button = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(88, 88, 88));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Settings");

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Choose Board:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Games History:");

        ExpandButton.setText("Expand Game");
        ExpandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpandButtonActionPerformed(evt);
            }
        });

        HistoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        HistoryList.setPreferredSize(new java.awt.Dimension(266, 212));
        HistoryListPane.setViewportView(HistoryList);

        javax.swing.GroupLayout HistoryPanelLayout = new javax.swing.GroupLayout(HistoryPanel);
        HistoryPanel.setLayout(HistoryPanelLayout);
        HistoryPanelLayout.setHorizontalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HistoryListPane, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        HistoryPanelLayout.setVerticalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryPanelLayout.createSequentialGroup()
                .addComponent(HistoryListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExpandButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExpandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout BoardPanelLayout = new javax.swing.GroupLayout(BoardPanel);
        BoardPanel.setLayout(BoardPanelLayout);
        BoardPanelLayout.setHorizontalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BoardPanelLayout.setVerticalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        Board1Button.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Board1Button.setText("Board 1");
        Board1Button.setPreferredSize(new java.awt.Dimension(100, 100));
        Board1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Board1ButtonActionPerformed(evt);
            }
        });

        Board2Button.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Board2Button.setText("Board 2");
        Board2Button.setPreferredSize(new java.awt.Dimension(100, 100));
        Board2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Board2ButtonActionPerformed(evt);
            }
        });

        Board3Button.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Board3Button.setText("Board 3");
        Board3Button.setPreferredSize(new java.awt.Dimension(100, 100));
        Board3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Board3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Board1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Board2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Board3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Board1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Board2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Board3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Choose Pieces:");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PiecesPanelLayout = new javax.swing.GroupLayout(PiecesPanel);
        PiecesPanel.setLayout(PiecesPanelLayout);
        PiecesPanelLayout.setHorizontalGroup(
            PiecesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PiecesPanelLayout.setVerticalGroup(
            PiecesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        Pieces1Button.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Pieces1Button.setText("Piece Set A");
        Pieces1Button.setPreferredSize(new java.awt.Dimension(100, 100));
        Pieces1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pieces1ButtonActionPerformed(evt);
            }
        });

        Pieces2Button.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Pieces2Button.setText("Piece Set B");
        Pieces2Button.setPreferredSize(new java.awt.Dimension(100, 100));
        Pieces2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pieces2ButtonActionPerformed(evt);
            }
        });

        Pieces3Button.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Pieces3Button.setText("Piece Set C");
        Pieces3Button.setPreferredSize(new java.awt.Dimension(100, 100));
        Pieces3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pieces3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PiecesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pieces1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pieces2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pieces3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pieces1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pieces2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pieces3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PiecesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        mainFrame.setNewPanel(new StartMenu(mainFrame));
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ExpandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpandButtonActionPerformed
        
        if(ExpandButton.getText().equals("Expand Game")){
           gameHistoryList = new DefaultListModel();
            for(int x=0; x<gamesHistory.get(HistoryList.getSelectedIndex()).size(); x++){
                gameHistoryList.addElement(gamesHistory.get(HistoryList.getSelectedIndex()).get(x));
            }

            HistoryList = new JList(gameHistoryList);
            HistoryListPane.setViewportView(HistoryList); 
            ExpandButton.setText("Back");
        }
        else{
            HistoryList = new JList(allHistoryList);
            HistoryListPane.setViewportView(HistoryList);
            ExpandButton.setText("Expand Game");
        }
        
    }//GEN-LAST:event_ExpandButtonActionPerformed

    private void Board1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Board1ButtonActionPerformed
        mainFrame.boardName = "board.png";
    }//GEN-LAST:event_Board1ButtonActionPerformed

    private void Board2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Board2ButtonActionPerformed
        mainFrame.boardName = "board2.png";
    }//GEN-LAST:event_Board2ButtonActionPerformed

    private void Board3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Board3ButtonActionPerformed
        mainFrame.boardName = "board3.png";
    }//GEN-LAST:event_Board3ButtonActionPerformed

    private void Pieces1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pieces1ButtonActionPerformed
        mainFrame.piecesName = "";
    }//GEN-LAST:event_Pieces1ButtonActionPerformed

    private void Pieces2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pieces2ButtonActionPerformed
        mainFrame.piecesName = "2";
    }//GEN-LAST:event_Pieces2ButtonActionPerformed

    private void Pieces3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pieces3ButtonActionPerformed
        mainFrame.piecesName = "3";
    }//GEN-LAST:event_Pieces3ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JToggleButton Board1Button;
    private javax.swing.JToggleButton Board2Button;
    private javax.swing.JToggleButton Board3Button;
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JButton ExpandButton;
    private javax.swing.JButton ExpandButton1;
    private javax.swing.JList<String> HistoryList;
    private javax.swing.JList<String> HistoryList1;
    private javax.swing.JScrollPane HistoryListPane;
    private javax.swing.JScrollPane HistoryListPane1;
    private javax.swing.JPanel HistoryPanel;
    private javax.swing.JPanel HistoryPanel1;
    private javax.swing.JToggleButton Pieces1Button;
    private javax.swing.JToggleButton Pieces2Button;
    private javax.swing.JToggleButton Pieces3Button;
    private javax.swing.JPanel PiecesPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
